### ISSUE TITLE
Installing into Python 3.9 and 3.10 environments pulls in the wrong version of jaxlib

### ISSUE THREAD

**Issue by lohedges** [alchemistry/alchemlyb#336] opened 2023-11-14 10:59 UTC
For some reason, when installing `alchemlyb` into a clean Python 3.9 environment it's pulling in the _wrong_ version of `jaxlib`, ie..:

```
mamba create -n test -c conda-forge alchemlyb python=3.9 
```

gives:

```
  + jax                        0.3.14  pyhd8ed1ab_0         conda-forge/noarch        846kB
  + jaxlib                     0.1.75  py39hde0f152_0       conda-forge/linux-64       57MB
```

When using the environment I get:

```python
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32)
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from alchemlyb.estimators import AutoMBAR
Warning on use of the timeseries module: If the inherent timescales of the system are long compared to those being analyzed, this statistical inefficiency may be an underestimate.  The estimate presumes the use of many statistically independent samples.  Tests should be performed to assess whether this condition is satisfied.   Be cautious in the interpretation of the data.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lester/.conda/envs/test/lib/python3.9/site-packages/alchemlyb/estimators/__init__.py", line 1, in <module>
    from .bar_ import BAR
  File "/home/lester/.conda/envs/test/lib/python3.9/site-packages/alchemlyb/estimators/bar_.py", line 3, in <module>
    from pymbar.other_estimators import bar as BAR_
  File "/home/lester/.conda/envs/test/lib/python3.9/site-packages/pymbar/__init__.py", line 32, in <module>
    from .mbar import MBAR
  File "/home/lester/.conda/envs/test/lib/python3.9/site-packages/pymbar/mbar.py", line 44, in <module>
    from pymbar import mbar_solvers
  File "/home/lester/.conda/envs/test/lib/python3.9/site-packages/pymbar/mbar_solvers.py", line 16, in <module>
    from jax.config import config
  File "/home/lester/.conda/envs/test/lib/python3.9/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/lester/.conda/envs/test/lib/python3.9/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config
  File "/home/lester/.conda/envs/test/lib/python3.9/site-packages/jax/_src/config.py", line 29, in <module>
    from jax._src import lib
  File "/home/lester/.conda/envs/test/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 94, in <module>
    version = check_jaxlib_version(
  File "/home/lester/.conda/envs/test/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 83, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib is version 0.1.75, but this version of jax requires version >= 0.3.7.
```

I thought that `jax` was pulled in via `pymbar`, but strangely I _don't_ see the version issue when installing `pymbar` by itself, i.e.:

```
mamba create -n test -c conda-forge pymbar python=3.9
```

gives:

```
  + jax                     0.4.19  pyhd8ed1ab_0             conda-forge/noarch          1MB
  + jaxlib                  0.4.19  cuda118py39h1ceb2bc_200  conda-forge/linux-64       99M
```

The issue isn't present for the other Python variants that I'm building against. (3.10 and 3.11.)

I've not confirmed whether this an issue with the `mamba` solver since using plain `conda` was taking too long to resolve.

Cheers.

**Comment by lohedges** [comment] 2023-11-14 11:04
Sorry, in case it wasn't obvious from the output, the above is on `linux-64`. I've not confirmed if the problem is also present on other platforms.

**Comment by lohedges** [comment] 2023-11-14 11:58
This also affects Python 3.10. (I must have used the wrong variant when testing earlier.) Python 3.11 is fine.

**Comment by orbeckst** [comment] 2023-11-15 07:12
Note that you shouldn't even be able to import AutoMBAR in the latest alchemlyb release as we removed it. Are you running 2.1.0?

It "works for me" in Python 3.9 on macOS and Linux. The tests also all pass. Can you check what versions of other relevant packages you have in your environments? Maybe there's a difference??

## Intel macOS 13.5.2

I can't reproduce on MacOS:
```
$ mamba create -n alchemlyb-336-py39 -c conda-forge alchemlyb python=3.9
$ mamba activate alchemlyb-336-py39
$ mamba list | egrep 'alchemlyb|pymbar|jax|numpy|pandas'
# packages in environment at ~/anaconda3/envs/alchemlyb-336-py39:
alchemlyb                 2.1.0              pyhd8ed1ab_0    conda-forge
jax                       0.4.19             pyhd8ed1ab_0    conda-forge
jaxlib                    0.4.16           py39h5c6ac89_0
numpy                     1.26.0           py39h5c76802_0    conda-forge
pandas                    2.1.3            py39h5d65943_0    conda-forge
pymbar                    4.0.2                h6e9494a_0    conda-forge
pymbar-core               4.0.2            py39h57e1da4_0    conda-forge
```

I can import `MBAR` without problems:

```python
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:52:10)
[Clang 15.0.7 ] on darwin
>>> from alchemlyb.estimators import MBAR
Warning on use of the timeseries module: If the inherent timescales of the system are long compared to those being analyzed, this statistical inefficiency may be an underestimate.  The estimate presumes the use of many statistically independent samples.  Tests should be performed to assess whether this condition is satisfied.   Be cautious in the interpretation of the data.

****** PyMBAR will use 64-bit JAX! *******
* JAX is currently set to 32-bit bitsize *
* which is its default.                  *
*                                        *
* PyMBAR requires 64-bit mode and WILL   *
* enable JAX's 64-bit mode when called.  *
*                                        *
* This MAY cause problems with other     *
* Uses of JAX in the same code.          *
******************************************

>>> import alchemlyb
>>> alchemlyb.__version__
'2.1.0'
```

## Linux Ubuntu 22.04 x86_64

I also can't reproduce in Linux:

```
$ mamba create -n alchemlyb-336-py39 -c conda-forge alchemlyb python=3.9
$ mamba activate alchemlyb-336-py39
$ mamba list | egrep 'alchemlyb|pymbar|jax|numpy|pandas'
# packages in environment at ~/miniconda3/envs/alchemlyb-336-py39:
alchemlyb                 2.1.0              pyhd8ed1ab_0    conda-forge
jax                       0.4.19             pyhd8ed1ab_0    conda-forge
jaxlib                    0.4.16           py39h6a678d5_0
numpy                     1.26.0           py39h474f0d3_0    conda-forge
pandas                    2.1.3            py39hddac248_0    conda-forge
pymbar                    4.0.2                hf3d152e_0    conda-forge
pymbar-core               4.0.2            py39h0f8d45d_0    conda-forge
```

MBAR loads just fine:

```python
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32)
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from alchemlyb.estimators import MBAR
Warning on use of the timeseries module: If the inherent timescales of the system are long compared to those being analyzed, this statistical inefficiency may be an underestimate.  The estimate presumes the use of many statistically independent samples.  Tests should be performed to assess whether this condition is satisfied.   Be cautious in the interpretation of the data.

****** PyMBAR will use 64-bit JAX! *******
* JAX is currently set to 32-bit bitsize *
* which is its default.                  *
*                                        *
* PyMBAR requires 64-bit mode and WILL   *
* enable JAX's 64-bit mode when called.  *
*                                        *
* This MAY cause problems with other     *
* Uses of JAX in the same code.          *
******************************************

>>> import alchemlyb
>>> alchemlyb.__version__
'2.1.0'
```

## Tests
In both environments I ran the tests in an identical manner (using xdist to run 4 processes in parallel) 
```
$ pip install alchemtest
$ mamba install pytest pytest-xdist
$ pytest -n 4 --pyargs alchemlyb.tests
```
The tests took a few minutes. They passed except one test
```
==================================================== short test summary info =====================================================
FAILED miniconda3/envs/alchemlyb-336-py39/lib/python3.9/site-packages/alchemlyb/tests/test_workflow_ABFE.py::TestInit::test_nofilematch - Failed: DID NOT RAISE <class 'ValueError'>
=============== 1 failed, 405 passed, 45 warnings in 499.80s (0:08:19) ================
```
(will have to look into it).

**Comment by lohedges** [comment] 2023-11-15 08:50
Thanks for the quick reply. This is what I see locally:

```python
$ mamba create -n alchemlyb-39 -c conda-forge alchemlyb python=3.9
$ mamba activate alchemlyb-39
$ mamba list | egrep 'alchemlyb|pymbar|jax|numpy|pandas
alchemlyb                 2.1.0              pyhd8ed1ab_0    conda-forge
jax                       0.3.14             pyhd8ed1ab_0    conda-forge
jaxlib                    0.1.75           py39hde0f152_0    conda-forge
numpy                     1.26.0           py39h474f0d3_0    conda-forge
pandas                    2.1.3            py39hddac248_0    conda-forge
pymbar                    4.0.1            py39h2ae25f5_1    conda-forge
```

And for Python 3.10:

```python
$ mamba create -n alchemlyb-310 -c conda-forge alchemlyb python=3.10
$ mamba activate alchemlyb-310
$ mamba list | egrep 'alchemlyb|pymbar|jax|numpy|pandas
alchemlyb                 2.1.0              pyhd8ed1ab_0    conda-forge
jax                       0.3.14             pyhd8ed1ab_0    conda-forge
jaxlib                    0.1.75          py310hb5077e9_0    conda-forge
numpy                     1.26.0          py310hb13e2d6_0    conda-forge
pandas                    2.1.3           py310hcc13569_0    conda-forge
pymbar                    4.0.1           py310hde88566_1    conda-forge
```

And trying to import `AutoMBAR` in either:

```python
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from alchemlyb.estimators import AutoMBAR
Warning on use of the timeseries module: If the inherent timescales of the system are long compared to those being analyzed, this statistical inefficiency may be an underestimate.  The estimate presumes the use of many statistically independent samples.  Tests should be performed to assess whether this condition is satisfied.   Be cautious in the interpretation of the data.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/alchemlyb/estimators/__init__.py", line 1, in <module>
    from .bar_ import BAR
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/alchemlyb/estimators/bar_.py", line 3, in <module>
    from pymbar.other_estimators import bar as BAR_
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/pymbar/__init__.py", line 32, in <module>
    from .mbar import MBAR
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/pymbar/mbar.py", line 44, in <module>
    from pymbar import mbar_solvers
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/pymbar/mbar_solvers.py", line 16, in <module>
    from jax.config import config
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/jax/_src/config.py", line 29, in <module>
    from jax._src import lib
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 94, in <module>
    version = check_jaxlib_version(
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 83, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib is version 0.1.75, but this version of jax requires version >= 0.3.7.
```

Same thing when just importing `MBAR`:

```python
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from alchemlyb.estimators import MBAR
Warning on use of the timeseries module: If the inherent timescales of the system are long compared to those being analyzed, this statistical inefficiency may be an underestimate.  The estimate presumes the use of many statistically independent samples.  Tests should be performed to assess whether this condition is satisfied.   Be cautious in the interpretation of the data.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/alchemlyb/estimators/__init__.py", line 1, in <module>
    from .bar_ import BAR
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/alchemlyb/estimators/bar_.py", line 3, in <module>
    from pymbar.other_estimators import bar as BAR_
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/pymbar/__init__.py", line 32, in <module>
    from .mbar import MBAR
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/pymbar/mbar.py", line 44, in <module>
    from pymbar import mbar_solvers
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/pymbar/mbar_solvers.py", line 16, in <module>
    from jax.config import config
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/jax/_src/config.py", line 29, in <module>
    from jax._src import lib
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 94, in <module>
    version = check_jaxlib_version(
  File "/home/lester/.conda/envs/test/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 83, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib is version 0.1.75, but this version of jax requires version >= 0.3.7.
```

This is reproducible on our CI too, which sets up a conda environment using the [setup-miniconda](https://github.com/conda-incubator/setup-miniconda) action.

> Note that you shouldn't even be able to import AutoMBAR in the latest alchemlyb release as we removed it. Are you running 2.1.0?

Yes, I was confused by this too, but as you can see I am using 2.1.0:

```
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import alchemlyb
>>> alchemlyb.__version__
'2.1.0'
```

Our code is actually agnostic to the `alchemlyb` API, i.e. we use `try/except` to import both MBAR variants. This is because some users haven't yet updated other tools to `pymbar` 4 so we don't want to pin `alchemlyb` to > 2.1.0.

Cheers.

**Comment by lohedges** [comment] 2023-11-15 08:58
Okay, I _can_ get it to work when pinning to `pymbar=4.0.2`, i.e.:

```python
$ mamba create -n test -c conda-forge alchemlyb pymbar=4.0.2 python=3.10
$ mamba activate test
$ mamba list | egrep 'alchemlyb|pymbar|jax|numpy|pandas
alchemlyb                 2.1.0              pyhd8ed1ab_0    conda-forge
jax                       0.4.19             pyhd8ed1ab_0    conda-forge
jaxlib                    0.4.19          cuda118py310ha8ecd4c_200    conda-forge
numpy                     1.26.0          py310hb13e2d6_0    conda-forge
pandas                    2.1.3           py310hcc13569_0    conda-forge
pymbar                    4.0.2                hff52083_0    conda-forge
pymbar-core               4.0.2           py310h278f3c1_0    conda-forge
```

I have no idea why the latest `pymbar` isn't being pulled in by default for me. Anyway, it appears that `pymbar`, and by association `alchemlyb`, is broken for `pymbar` version 4.0.1.

**Comment by orbeckst** [comment] 2023-11-15 15:40
Perhaps dependencies are resolved differently in our systems?

```
 mamba --version
```
* my macOS: mamba 1.4.2, conda 23.3.1
* my Linux: mamba 1.4.9, conda 23.5.2

(In other circumstances I got very weird behavior when I installed additional packages into an existing environment, especially if I had to pull from other channels (e.g., suddenly PyPy version of python was installed and other packages  uninstalled...) but none of this should matter with a fresh environment.)

Channels:
```
mamba info
```

macOS
```
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
```

Linux
```
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
```

**Comment by orbeckst** [comment] 2023-11-15 15:41
> Anyway, it appears that pymbar, and by association alchemlyb, is broken for pymbar version 4.0.1.

We could bump the requirement to `pymbar >= 4.0.2` if this is a persistent issue, e.g., if other people also report it. @xiki-tempula did you see this problem in the wild?

**Comment by lohedges** [comment] 2023-11-15 16:03
> Perhaps dependencies are resolved differently in our systems?

Presumably so, but I've tried in a clean Miniforge install with the same channel URLs. (We also use a clean Miniforge for our CI.)

>   Is this a known issue with the installation of pymbar 4.0.1?

I couldn't find anything on their issue trackers. (Both the GItHub repo and the feedstock repo.) Bizarrely, if I install `pymbar` version `4.0.1` by itself, then everything is fine:

```
$ mamba create -n test -c conda-forge pymbar=4.0.1
$ mamba activate test
$ mamba list jax
jax                       0.4.19             pyhd8ed1ab_0    conda-forge
jaxlib                    0.4.19          cuda118py311h045a74e_200    conda-forge
```
I'm guessing it's an interplay between `pymbar` and some of your other dependencies. Perhaps pinning is off for  `jax`  and `jaxlib` for `pymbar=4.0.1` so an incorrect version can get pulled in depending on what else is being resolved at the same time.

**Comment by xiki-tempula** [comment] 2023-11-16 09:41
I'm not quite sure of what is the best way to tackle this problem. The dependency list of alchemlyb is quite simple, where we just depends on pymbar and pymbar pulls in Jax. Jax then pulls in Jaxlib.
So whether it should be in the alchemlyb dependency to solve this alloying jaxlib problem is a bit difficult to answer. One difficulty would be that if we do the pinning at a later version. conda might try to resolve the env by providing a earlier version of alchemlyb, which is not what we really want.
In my production env, I kind of pin the jaxlib at the final level.

**Comment by mattwthompson** [comment] 2023-12-30 03:47
This is a [known upstream](https://github.com/conda-forge/pymbar-feedstock/issues/30) issue which I don't think ever got completely fixed. There are some weird things in old `jaxlib` builds that cause this specific incompatibility and were resolved where in the 0.3.x line. (Constraining the `pymbar` versions might help, but isn't [the root of the headache](https://github.com/conda-forge/jax-feedstock/issues/81).) They ought to be patched, but the simplest and effective-enough solution is to just [ensure the solver never looks at](https://github.com/conda-forge/pymbar-feedstock/pull/33/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR35-R36) old `jaxlib` builds; this works whether or not it's considered a required dependency. This probably requires patching repodata, which is hard to avoid these days.

**Comment by lohedges** [comment] 2024-01-08 13:30
Thanks for the insight, @mattwthompson. Much appreciated.

**Comment by orbeckst** [comment] 2024-04-01 08:32
I don't think that there's much we can do about it here so I am closing.

**Closed by orbeckst** 2024-04-01 08:32 UTC
Labels: wontfix, installation
