### ISSUE TITLE
problem with energy convertor

### ISSUE THREAD

**Issue by maryam-amin** [alchemistry/alchemlyb#178] opened 2021-11-23 10:25 UTC
I'm new to alchemlyb and python programming and want to  analyze free energy calculations (Gromacs-based) using alchemlyb and I want to implement postprocessing to convert energy units to KJ/mol, with the following python script:

```python
import pandas as pd
import numpy as np
import alchemlyb
from alchemlyb.estimators import AutoMBAR as MBAR
from alchemlyb.postprocessors.units import to_kcalmol, to_kJmol, to_kT

#extract data
xvgs=('/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0000.xvg', '/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0001.xvg', '/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0002.xvg', '/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0003.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0004.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0005.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0006.xvg', '/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0007.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0008.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0009.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0010.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0011.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0012.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0013.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0014.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0015.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0016.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0017.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0018.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0019.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0020.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0021.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0022.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0023.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0024.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0025.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0026.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0027.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0028.xvg','/home/home/CO2-solvation/dhdl/dhdl-0-29/dhdl.part0029.xvg')

mbar=MBAR().fit(u_nk)
mbar_f=mbar.delta_f_
#print('free energy is', mbar_f)
EU=delta_f_.attrs
print('energy unit is', EU)
delta_f_=to_kJmol(mbar_f.delta_f_)
EU=delta_f_.attrs
print('energy unit is', EU)
```

**But I encounter the following error:**
```
File "/home/home/alchemlyb/src/alchemlyb/alchemical-calc.py", line 27, in <module>
    EU=delta_f_.attrs
NameError: name 'delta_f_' is not defined
```

**Comment by orbeckst** [comment] 2021-11-23 17:57
It looks as if you didn't define the variable `delta_f_` (even though the code above seems to define it).

I would try running each step interactively in ipython or Jupyter Lab. Look at the output. Does the output contain what you expect? The first step that fails is the first problem to solve. Let us know which step it is.

**Comment by orbeckst** [comment] 2021-11-23 17:59
Note that the [energy unit](https://alchemlyb.readthedocs.io/en/latest/parsing.html#a-note-on-units) is
```python
EU = mbar.delta_f_.attrs['energy_unit']
```

**Comment by maryam-amin** [comment] 2021-11-27 06:50
Sorry for my delay.
I can't find the output that you were mentioned. Where can I gain them?

**Comment by orbeckst** [comment] 2021-12-08 00:48
Your error
```
File "/home/home/alchemlyb/src/alchemlyb/alchemical-calc.py", line 27, in <module>
    EU=delta_f_.attrs
NameError: name 'delta_f_' is not defined
```
comes from the fact that you don't have the variable `delta_f` define. 

Try
```python
mbar = MBAR().fit(u_nk)

print('MBAR free energy output is', mbar.delta_f_)

print('energy unit is',  mbar.delta_f_.attrs['energy_unit'])
print('free energy difference is', mbar.delta_f_.loc[0.00, 1.00])

delta_f_kJmol = to_kJmol(mbar_f.delta_f_)
print('energy unit is', delta_f_kJmol.attrs['energy_unit'])
print('free energy difference is now', delta_f_kJmol.loc[0.00, 1.00])
```

**Comment by maryam-amin** [comment] 2021-12-08 07:54
I try what you recommend but the following error happened
print('energy unit is',  mbar.delta_f_.attrs['energy_unit'])
KeyError: 'energy_unit'

**Comment by xiki-tempula** [comment] 2021-12-08 09:40
@maryam-amin What version of alchemlyb are you using? Would you mind try the latest version pulled from the github?

**Comment by maryam-amin** [comment] 2021-12-08 11:33
The latest version, I have recently downloaded alchemlyb from the github.

**Comment by xiki-tempula** [comment] 2021-12-08 12:01
@maryam-amin That's weird, do you mind sharing your files and the script?

**Comment by orbeckst** [comment] 2021-12-08 15:44
Can you tell us what 

print(alchemlyb.__version__)

gives?

Please describe (with code) how you installed alchemlyb.

Thanks.

**Comment by maryam-amin** [comment] 2021-12-08 18:09
My script is this:
import pandas as pd
import numpy as np
import alchemlyb
import glob
from alchemlyb.parsing.gmx import extract_u_nk
from alchemlyb.preprocessing import slicing
from alchemlyb.postprocessors.units import to_kcalmol, to_kJmol, to_kT
from alchemlyb.estimators import AutoMBAR as MBAR

#extract data
xvgs=('/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0000.xvg', '/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0001.xvg', '/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0002.xvg', '/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0003.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0004.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0005.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0006.xvg', '/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0007.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0008.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0009.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0010.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0011.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0012.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0013.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0014.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0015.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0016.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0017.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0018.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0019.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0020.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0021.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0022.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0023.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0024.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0025.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0026.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0027.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0028.xvg','/home/home/OH-solvation/dhdl/dhdl-0-29/dhdl.OHpart0029.xvg')
#xvgs=('/home/home/MEA-solvation/dhdl/dhdl-0-29/dhdl.part0028.xvg', '/home/home/MEA-solvation/dhdl/dhdl-0-29/dhdl.part0029.xvg')
u_nk = pd.concat([extract_u_nk(xvg, T=293.15) for xvg in xvgs])
u_nk = u_nk.sort_values(['time','coul-lambda','vdw-lambda'], ascending=[True,True,True])
u_nk.shape
u_nk=alchemlyb.concat([slicing(u_nk, lower=2500, upper=10500, step=1,force=True)])
print('=>',u_nk)
mbar = MBAR().fit(u_nk)

print('MBAR free energy output is', mbar.delta_f_)

print('energy unit is',  mbar.delta_f_.attrs['energy_unit'])
print('free energy difference is', mbar.delta_f_.loc[0.00, 1.00])

delta_f_kJmol = to_kJmol(mbar_f.delta_f_)
print('energy unit is', delta_f_kJmol.attrs['energy_unit'])
print('free energy difference is now', delta_f_kJmol.loc[0.00, 1.00])

**Comment by xiki-tempula** [comment] 2021-12-08 18:12
@maryam-amin Would you replace all `pd.concat` with `alchemlyb.concat`?

**Comment by maryam-amin** [comment] 2021-12-08 18:14
versioneer-0.18
One of my classmates installed the program for me in Linux-Ubuntu.

**Comment by maryam-amin** [comment] 2021-12-08 18:27
I replaced it, but the same error happened.
print('energy unit is',  mbar.delta_f_.attrs['energy_unit'])
KeyError: 'energy_unit'

**Comment by xiki-tempula** [comment] 2021-12-08 18:30
@maryam-amin Do you mind do

```
u_nk = alchemlyb.concat([extract_u_nk(xvg, T=293.15) for xvg in xvgs])
print(u_nk.attrs)
u_nk = u_nk.sort_values(['time','coul-lambda','vdw-lambda'], ascending=[True,True,True])
print(u_nk.attrs)
u_nk.shape
u_nk=alchemlyb.concat([slicing(u_nk, lower=2500, upper=10500, step=1,force=True)])
print(u_nk.attrs)
print('=>',u_nk)
mbar = MBAR().fit(u_nk)
print(mbar.delta_f_.attrs)
delta_f_kJmol = to_kJmol(mbar_f.delta_f_)
print(delta_f_kJmol.delta_f_.attrs)
```
So we can track where did the unit got lost.

**Comment by maryam-amin** [comment] 2021-12-08 19:11
It seems that it proceeds but the following error happened:
File "/home/home/alchemlyb/src/alchemlyb/alchemical-calc.py", line 23, in <module>
    delta_f_kJmol = to_kJmol(mbar_f.delta_f_)
NameError: name 'mbar_f' is not defined

**Comment by xiki-tempula** [comment] 2021-12-09 09:04
@maryam-amin This `delta_f_kJmol = to_kJmol(mbar_f.delta_f_)` should be `delta_f_kJmol = to_kJmol(mbar.delta_f_)`

**Comment by orbeckst** [comment] 2021-12-27 19:49
@maryam-amin did @xiki-tempula 's last comment solve your problem? If so please let us know so that we can close the issue and anyone else finding the issue will know how to solve the problem.

You may also close the issue yourself.

If we don't hear from you in a week we'll simply close the issue and assume that the issue is not relevant to you anymore.

**Closed** 2021-12-28 07:25 UTC
Labels: question
