### ISSUE TITLE
plot_mbar_overlap_matrix(mbar_coul.overlap_matrix) Error

### ISSUE THREAD

**Issue by jinfeng-data** [alchemistry/alchemlyb#251] opened 2022-10-16 09:25 UTC
Hi,

I want to reproduce the overlap matrix of the MBAR by running the provided examples as follows,

**import pandas as pd
from alchemtest.gmx import load_benzene
from alchemlyb.parsing.gmx import extract_u_nk
from alchemlyb.estimators import MBAR
bz = load_benzene().data
u_nk_coul = alchemlyb.concat([extract_u_nk(xvg, T=300) for xvg in bz['Coulomb']])
mbar_coul = MBAR()
mbar_coul.fit(u_nk_coul)
from alchemlyb.visualisation import plot_mbar_overlap_matrix
ax = plot_mbar_overlap_matrix(mbar_coul.overlap_matrix)**

However, I got an error message as the following,

_>>> ax = plot_mbar_overlap_matrix(mbar_coul.overlap_matrix)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jinfeng/soft/miniconda3/lib/python3.8/site-packages/alchemlyb/estimators/mbar_.py", line 137, in overlap_matrix
    return self._mbar.computeOverlap()['matrix']
TypeError: tuple indices must be integers or slices, not str_

So, what should I do to solve the above problem ? For your convenience, the version of my alchemlyb is 0.7.0. Thanks in advance !

Best,
Jinfeng

**Comment by xiki-tempula** [comment] 2022-10-16 09:59
Thanks for reporting. It seems to me that this is a pymbar 4 issue. I wonder if you are using pymbar4? 

As is mentioned in #207, we currently don't support pymbar 4 and plan to support it once we get 1.0 out. I wonder how you install alchemlyb? Conda should only allow pymbar<4 to be installed so I might need to check how pymbar 4 creep in.

**Comment by jinfeng-data** [comment] 2022-10-16 10:40
Hi,

I am using pymbar3.0.1beta0. I install the alchemlyb from the source by using pip install.  Thanks!

**Comment by xiki-tempula** [comment] 2022-10-16 10:43
@jinfeng-data I see. I guess the issue is the other way around then. I think if you install the latest version of pymbar 3, it should work.
I would recommend using conda to setup the environment as pip will usually mess the environment up.

**Comment by jinfeng-data** [comment] 2022-10-16 12:37
Hi,

As you recommended, I install alchemlyb by using conda, and it help me to install alchemlyb 0.7.0 and pymbar 3.1. However when running, I come across another problem as the following,

_943 MBAR energies are > 0.0 kcal/mol
814 MBAR energies are > 0.0 kcal/mol
1038 MBAR energies are > 0.0 kcal/mol
Traceback (most recent call last):
  File "TI_mbar.py", line 30, in <module>
    com_mbar = MBAR().fit(com_u_nk)
  File "/home/jinfeng/soft/miniconda3/lib/python3.8/site-packages/alchemlyb/estimators/mbar_.py", line 92, in fit
    self._mbar, out = self._do_MBAR(u_nk, N_k, solver_protocol)
  File "/home/jinfeng/soft/miniconda3/lib/python3.8/site-packages/alchemlyb/estimators/mbar_.py", line 120, in _do_MBAR
    out = mbar.getFreeEnergyDifferences(return_theta=True)
  File "/home/jinfeng/soft/miniconda3/lib/python3.8/site-packages/pymbar/mbar.py", line 586, in getFreeEnergyDifferences
    Theta_ij = self._computeAsymptoticCovarianceMatrix(
  File "/home/jinfeng/soft/miniconda3/lib/python3.8/site-packages/pymbar/mbar.py", line 1735, in _computeAsymptoticCovarianceMatrix
    check_w_normalized(W, N_k)
  File "/home/jinfeng/soft/miniconda3/lib/python3.8/site-packages/pymbar/utils.py", line 358, in check_w_normalized
    raise ParameterError(
pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 0 was 6.596104. 14 other columns have similar problems_

Is there anything wrong with my installation ?

**Comment by xiki-tempula** [comment] 2022-10-16 16:12
This is an annoying pymbar issue. You might want to try the alchemlyb.estimators.AutoMBAR

**Comment by orbeckst** [comment] 2022-10-18 21:50
I am closing this issue as the discussion moved towards AutoMBAR. If you want to continue the discussion please use the [Discussions](https://github.com/alchemistry/alchemlyb/discussions) forum. Thanks!

**Closed by orbeckst** 2022-10-18 21:50 UTC
